#start
title: 夜的第七章
mail: lwdggm@gmail.com
description: 夜的第七章-个人博客
author: lwdgit
github: https://github.com/lwdgit
mail: lwdggm@gmail.com
logo: https://avatars2.githubusercontent.com/u/5530205?v=3
dataSource: blog
rss_path: ./feed.xml
#end


paginate:     20   # 每页显示20条

# Build settings
markdown_ext: mdxxx # 防止md文件被编译
paginate_path: ./page/:num/
permalink:     ./post/:categories/:year-:month-:day-:title:output_ext
source:  .
include: ["admin"]
exclude: ["node_modules", "scripts"]

destination:      ./.site
layouts_dir:      ./_layouts

excerpt_separator: <!--more-->  # you can specify your own separator, of course.

defaults:
  - scope:
      path: "_posts" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "posts"
      comments: false
      category: "未归类"

